name: Boudoir Secrets
favicon: null
layout_spectrum: 0.09266278194263577
typography_spectrum: 0.26510345400311053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.03263214789330959
  lightness: 0.19932417594827712
  saturation: 0.006261526374146342
  rhythmicContrast: 0.37335230386815965
purpose: []
